version: '3'

services:
    react:
        build:
            context: .
            dockerfile: docker/react/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
